### ISSUE TITLE
Post title link on index page error

### ISSUE THREAD

**Issue by arjunsajeev** [poole/lanyon#108] opened 2015-04-29 04:58 UTC
Post title link in the index page is  not working for repositories of the type `username.github.io`.It generates links of the form `http://0.0.7.223/04/29/new-blog-post/`I think the post title link in the index page only requires `{{ post.url }}` instead of `{{ site.baseurl }}/{{ post.url }}`

**Comment by jakefb** [comment] 2015-05-06 07:08
I'm having the same issue :(

**Comment by Siyfion** [comment] 2015-05-13 18:07
I am also suffering from this issue, however it could be a configuration thing that I'm missing... (Sorry @mdo if this is spurious!)

**Comment by gogozs** [comment] 2015-05-23 16:04
comment out `url` line, and set `baseurl: ""`.

 works for me on github user page.

**Comment by ryano88** [comment] 2015-05-23 20:54
The correct fix for this is to leave _config.yml as it is and change

    {{site.baseurl}}/{{post.url}}

To

    {{site.baseurl}}{{post.url}}

In index.html

The problem is caused by the fact that `{{post.url}}` has a leading `/`

**Comment by jakefb** [comment] 2015-05-24 00:58
Worked for me thanks @ryano88!

**Comment by wireddown** [comment] 2015-08-15 16:22
In short, here are the best practices for User pages:

## _config.yml
* `baseurl` must be empty

## Theme layouts and includes
* Always concatenate Jekyll and Liquid tags in links, eg: `href="{{ site.baseurl }}{{ post.url }}"`
* Always start links with `{{ site.baseurl }}`
* Otherwise, always use a trailing slash after `{{ site.baseurl }}` in links

More details and command-line validation: [Configuring Jekyll for User and Project GitHub Pages](http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/)

**Comment by Autodidact24** [comment] 2015-09-06 07:16
Hi,
I was able to solve this issue as suggested by @ryano88. However, when clicking to the title, the page that appears is ill formatted.
My blog can be found here: http://shubhamtomar.me/
Try clinking on any title: http://shubhamtomar.me/2015/05/15/Twitter-Sentiment-Analysis/.

**Comment by wireddown** [comment] 2015-09-06 14:14
Your `head.html` include page has an incorrect link to the CSS, so the Lanyon styling is never loaded. Change its `href` URLs to `{{ site.baseurl }}/public/css/lanyon.css`; notice the slash before public. See the last bullet in my response above, or visit my link for instructions on how to inspect the rest of your site for correctness.

**Closed** 2016-03-26 12:10 UTC

**Comment by socpriya** [comment] 2016-09-17 23:43
Worked for me. 
Thanks @ryano88!!!

**Comment by keeprock** [comment] 2018-03-06 03:56
@ryano88 thanks for saving my precious time! Have a great day, brother!
