### ISSUE TITLE
Navbar open/close moves the page to the top

### ISSUE THREAD

**Issue by rom1v** [poole/lanyon#192] opened 2017-01-06 21:49 UTC
Since commit f039ccba3347ff8cebb6baea08efa01da497d6a3 (found through `git bisect`), opening/closing the navbar moves the page to the top, which is very annoying.

Reverting a part of the patch avoids the problem:
~~~diff
diff --git a/public/css/lanyon.css b/public/css/lanyon.css
index bc1408f..50bd789 100644
--- a/public/css/lanyon.css
+++ b/public/css/lanyon.css
@@ -202,6 +202,7 @@ a.sidebar-nav-item:focus {
 
 /* Hide the sidebar checkbox that we toggle with `.sidebar-toggle` */
 .sidebar-checkbox {
+  display: none;
   position: absolute;
   opacity: 0;
   -webkit-user-select: none;
~~~

cc @mdo

**Comment by mdo** [comment] 2020-04-03 04:07
Duplicate of #137.

**Closed by mdo** 2020-04-03 04:07 UTC
